### ISSUE TITLE
[Feature Request]: Adding a github action to the repository for issues and PRs

### ISSUE THREAD

**Issue by Jassi10000-zz** [open-certs/oc-frontend#11]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

While opening issues  / making PRs ,keeping a check of few things is very necessary 
* Providing a valid title 
* Provding a nice description
* While making the PR , tagging the issue 

### Proposed Solution

For this I would like to add a github action to this repository 

### Alternatives Considered

None

### Additional Information

Am a GSSOC'22 participant , can you please assign this task to me if this seems interesting

**Comment by Adi-11** [comment]
Ok Assigned
