### ISSUE TITLE
[Feature Request]: Error Handling

### ISSUE THREAD

**Issue by Adi-11** [open-certs/oc-frontend#14]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

Need for improving error and success message such as:
- Showing error message when an invalid entry is made in input field during certificate generation
- Success or failure message after login

and other places also where required.

### Proposed Solution

This feature can be implemented using any toasty module which suits best the current UI of the website.
e.g. 
- [notistack](https://www.npmjs.com/package/notistack)
- [react-toastify](https://www.npmjs.com/package/react-toastify)
- or any other toast notification module that is compactable with `Tailwind CSS`. 

### Alternatives Considered

NA

**Comment by Sumit-Anand3098** [comment]
I am interested to solve this issue

**Comment by Adi-11** [comment]
Ok Assigned

**Comment by Shubham-Kumar-2000** [comment]
HI @Rudra-Blazee  whats the update on this?

**Comment by Sumit-Anand3098** [comment]
I have some issue in my laptop, it will be resolved within this week and afterwards will give you update

**Comment by Sayan-dev** [comment]
I can pick up the Issue and finish it by today

**Comment by Adi-11** [comment]
ok Assigned, go ahead

**Comment by Sayan-dev** [comment]
Ok
