### ISSUE TITLE
[Feature Request]: verification page for certificate

### ISSUE THREAD

**Issue by Adi-11** [open-certs/oc-frontend#15]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

Once any certificate is generated there is a need for a verification page on our website. Where anyone who wants to validate the authenticity of any certificate, can put the unique ID on the certificate and can see the certificate.

### Proposed Solution

Add a Verificate page on the website, and load the certificate or give an error message when any ID is given to the input field.

### Alternatives Considered

NA

**Comment by MadhusreeBera** [comment]
Hello, I am a GSSoC'22 participant and I have some experience in front-end development. Could you please assign this issue to me if it is available

**Comment by Adi-11** [comment]
Ok, assign go ahead @MadhusreeBera
