### ISSUE TITLE
[Bug]: Header font color corrected

### ISSUE THREAD

**Issue by MadhusreeBera** [open-certs/oc-frontend#17]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.1.0

### What arch are you using?

x64

### Current Behavior

The Header font was incorrect as it was same as the header background. 

![image](https://user-images.githubusercontent.com/73298219/157086195-fc813eb3-09d9-4df6-b26c-5af2c4823f2d.png)

### Expected Behavior

Corrected the header font for both dark theme and light theme

**Comment by MadhusreeBera** [comment]
Please assign this issue to me.

**Comment by Adi-11** [comment]
Ok assigned
