### ISSUE TITLE
[Bug]: Could Not Log in

### ISSUE THREAD

**Issue by Sayan-dev** [open-certs/oc-frontend#21]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.1.0

### What arch are you using?

x64

### Current Behavior

After github oauth login, App throws Invalid Token Error even though successfully authenticated. (200 response from backend)

### Expected Behavior

After github oauth login, App should login.

**Comment by Sayan-dev** [comment]
I have found the bug, assign it to me @Adi-11

**Comment by Adi-11** [comment]
@Sayan-dev could you please attach a screenshot or a video reference reflecting this bug?

**Comment by Sayan-dev** [comment]
![ocerror](https://user-images.githubusercontent.com/42710260/157861100-ba9e7eec-f208-4d75-8200-d0db8bfb9ef6.png)
![oc-2](https://user-images.githubusercontent.com/42710260/157861109-66424334-d6c8-48e5-ad17-0b0263872f05.png)

**Comment by Sayan-dev** [comment]
I have found the Issue Just let me add a PR

**Comment by Adi-11** [comment]
Do you have `.env` file in your local repo?

**Comment by Sayan-dev** [comment]
Yes

**Comment by Adi-11** [comment]
ok assigned
