### ISSUE TITLE
[Bug]: Gitlab and Bitbucket auth in home page

### ISSUE THREAD

**Issue by MadhusreeBera** [open-certs/oc-frontend#25]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Version

0.1.0

### What arch are you using?

x64

### Current Behavior

The login buttons of Bitbucket and Gitlab in home page is not implemented 

### Expected Behavior

The login buttons of Bitbucket and Gitlab in home page should work

**Comment by MadhusreeBera** [comment]
Please assign this bug to me.

**Comment by Adi-11** [comment]
Ok assigned
