### ISSUE TITLE
[Feature Request]: Add 404 page

### ISSUE THREAD

**Issue by rsinghcodes** [open-certs/oc-frontend#36]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

When I am hitting on wrong route, a white blank page is shown.

There should be a 404 page with the appropriate information.

### Proposed Solution

I want to add 404 page with well designed UI and with graphics or illustration and with some appropriate information like we should inform the user that he has jumped or redirected to wrong page or the page he is trying to find is not available.

Please assign this issue to me under **GSSOC '22**.

Thanks!

**Comment by Adi-11** [comment]
@rsinghcodes Ok assigned, go ahead.

**Comment by rsinghcodes** [comment]
I'm not able to install dependencies locally to run the project.

![image](https://user-images.githubusercontent.com/67682451/161594167-66c9a63b-e02a-465c-939e-c967c204dfb5.png)

**Comment by Shubham-Kumar-2000** [comment]
Use `yarn`

**Comment by Adi-11** [comment]
> I'm not able to install dependencies locally to run the project.
> 
> ![image](https://user-images.githubusercontent.com/67682451/161594167-66c9a63b-e02a-465c-939e-c967c204dfb5.png)

@rsinghcodes 
Look in the project we are using `yarn` package manager, so please do all the installations with that only.

**Comment by rsinghcodes** [comment]
I am facing the same problem with `yarn` again.

Please also provide a way to use `npm`.

**Comment by Adi-11** [comment]
> I am facing the same problem with `yarn` again.
> 
> Please also provide a way to use `npm`.

@rsinghcodes  Ping me on discord, we can connect for this issue over there
