### ISSUE TITLE
[Feature Request]: get project data before generating certificate

### ISSUE THREAD

**Issue by ak3264114** [open-certs/oc-frontend#44]
### Preflight Checklist

- [x] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

Add a new page which show all data related to the project before generating certificate

### Proposed Solution

When user will click on fetch project it will navigate to a page, which display all the data related to the project and then user can generate their certificate

### Alternatives Considered

N/A

**Comment by ak3264114** [comment]
Please assign this issue to me.

**Comment by Adi-11** [comment]
ok assigned
