### ISSUE TITLE
[Feature Request]: Dark and Light Theme

### ISSUE THREAD

**Issue by Adi-11** [open-certs/oc-frontend#8]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

The website needs to have both light and dark theme UI, for better UX and more usability.

### Proposed Solution

We can use the theme system of `tailwind CSS` itself for the required purpose. 

### Alternatives Considered

NA

**Comment by MadhusreeBera** [comment]
Hello, I am a GSSoC'22 participant and I have some experience in front-end development. Could you please assign this issue to me if it is available

**Comment by Adi-11** [comment]
Ok Assigned.

**Comment by shelabh** [comment]
I am also interested in this project, may I also contribute to this issue.

**Comment by Adi-11** [comment]
> I am also interested in this project, may I also contribute to this issue.

@shelabh this issue is already assigned, You may choose another issue or can create your own issue to work with.

**Comment by flow6979** [comment]
if the one who is assigned this issue would be unable to solve it. you can assign this to me. thank you

**Comment by shelabh** [comment]
> > I am also interested in this project, may I also contribute to this issue.
> 
> @shelabh this issue is already assigned, You may choose another issue or can create your own issue to work with.

okay thanks, but if this issues is still unsolved , consider me
