### ISSUE TITLE
[Feature Request]: Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Susmita-Dey** [open-certs/oc-frontend#9]
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the issue for a feature request that matches the one I want to file, without success.

### Problem Description

CODE_OF_CONDUCT file is missing in this repository.

### Proposed Solution

I want to add the CODE_OF_CONDUCT.md file to this repo.

### Alternatives Considered

No alternatives.

### Additional Information

**I am contributor at GSSoC'22. Please assign this issue to me.**

**Comment by Adi-11** [comment]
Ok Assigned

**Comment by Susmita-Dey** [comment]
Thanks for assigning it to me.
